### ISSUE TITLE
Additional routes

### ISSUE THREAD

**Issue by sfabriece** [rcorral/hapi-restful-api-example#1]
Hi, could you demonstrate how to add an additional route to a different resource than task.

I want to see how to compose the plugin and so on.

Thanks.

**Comment by osukaa** [comment]
You could just duplicate the file and change the routes and filename. Then you register the plugin in the array. like this: 

```
var plugins = [
    {
        register: require('./routes/tasks.js'),
        options: {
            database: database
        }
    },
    {
        register: require('./routes/otherResource.js'),
        options: {
            database: database
        }
    }
];
```

**Comment by lifehome** [comment]
Perhaps this should be closed?
